### PR TITLE
UC php plugin version update

### PR DESCRIPTION
**Pull request by dimaninc**

### CODE REVIEW

**Comment by sokrat** [comment]
version 1.5 already exists?

**Comment by dimaninc** [comment]
yep
and it has some interesting new features like new pagination system using iterators

**Comment by sokrat** [comment]
I can't find it, latest release is [1.4.1](https://github.com/uploadcare/uploadcare-php/releases/tag/v1.4.1)

**Comment by dimaninc** [comment]
yep, my fault
added [1.5.0](https://github.com/uploadcare/uploadcare-php/releases/tag/v1.5.0) release

**Pull request merged**
